[project]
name = "rrr-rss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attrs>=25.3.0",
    "beautifulsoup4>=4.13.3",
    "html5lib>=1.1",
    "httpx>=0.28.1",
    "ipython>=9.0.2",
    "podgen>=1.1.0",
]
