name: Sync

on:
  workflow_dispatch:
  schedule:
  - cron: 0 */6 * * *

jobs:
  build-and-deploy:
    name: Sync and generate RSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Set up FFMPEG
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_KEY: ${{ secrets.B2_KEY }}
          BUCKET_ID: ${{ secrets.BUCKET_ID }}
        run: |
          uv run python main.py
